version: '2.1'

services:
  # Postgres container
  db:
    image: postgres:9.6-alpine
    container_name: postgres
    env_file: .env
    expose:
     - 5432

  # Backend API container
  backend:
    container_name: backend
    build: ./poll-backend
    working_dir: /build
    volumes:
      - ./poll-backend:/build/
    env_file: .env
    command: /start.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  # Frontend container
  frontend:
    container_name: frontend
    build: ./poll-frontend
    working_dir: /build
    volumes:
      - ./poll-frontend:/build/
    links:
      - backend
    ports:
      - "5000:5000"
    restart: always
