# Generated by Django 2.0 on 2018-01-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question'),
        ),
    ]
